app = "alistfile"
primary_region = "lax" #https://fly.io/docs/reference/regions/

[build]

[env]
  PORT = "5244"

[[mounts]]
  source = "data" #https://fly.io/docs/apps/volume-storage/
  destination = "/opt/alist/data"

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
