app = "change-this-app-name"
primary_region = "hkg" #https://fly.io/docs/reference/regions/

[build]

[env]
  PORT = "5244"

[[mounts]]
  source = "change-this-storage-name" #https://fly.io/docs/apps/volume-storage/
  destination = "/opt/alist/data"

[http_service]
  internal_port = 5244
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]